//
//   Copyright 2013 Sougata Sarkar
//
//   This file is part of Jobtracker.

//   Jobtracker is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
//   License as published by the Free Software Foundation, either version 3 of the License, or (at your option) 
//   any later version.
//
//   JobTracker is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
//   implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
//   for more details.
//
//   You should have received a copy of the GNU General Public License along with Jobtracker. If not, 
//   see http://www.gnu.org/licenses/.
//


var defaultPrintJobTpl = Ext.create('Ext.XTemplate',
'<tpl for=".">',
    '<div class="printJobSelectBox" id="{JobID}">',
        '<div style="clear:left;float:left">',
            '<table>',
                '<tr>',
                    '<td style="vertical-align:top">',
                        '<div style="text-align:top;">',
                            '<table border="0">',
                                '<tr>',
                                    '<td colspan="2">',
                                        '<div style="margin-bottom:5px;">',
                                            '<table>',
                                                '<tr>',
                                                    '<td width="80px" style="align:left"><b>Job #:</b></td>',
                                                    '<td><span style="color:#2e408c"><b>{JobNo}</b></span></td>',
                                                '</tr>',
                                            '</table>',
                                        '</div>',
                                    '</td>',
                                '</tr>',
                                '<tr>',
                                    '<td>',
                                        '<div style="margin-bottom:5px;">',
                                            '<table>',
                                                '<tr>',
                                                    '<td width="80px" style="align:left">PO #:</td>',
                                                    '<td><span>{PONo}</span></td>',
                                                '</tr>',
                                            '</table>',
                                        '</div>',
                                    '</td>',
                                    '<td>',
                                        '&nbsp;',
                                    '</td>',
                                '</tr>',
                                '<tr>',
                                    '<td>',
                                        '<div style="margin-bottom:5px;">',
                                            '<table>',
                                                '<tr>',
                                                    '<td width="80px" style="align:left">Dispatch #:</td>',
                                                    '<td><span>{DispatchNo}</span></td>',
                                                '</tr>',
                                            '</table>',
                                        '</div>',
                                    '</td>',
                                    '<td>',
                                        '&nbsp;',
                                    '</td>',
                                '</tr>',
                                '<tr>',
                                    '<td>',
                                        '<div style="margin-bottom:5px;">',
                                                '<table>',
                                                '<tr>',
                                                    '<td width="80px" style="align:left">Serial #:</td>',
                                                    '<td><span>{SerialNo}</span></td>',
                                                '</tr>',
                                            '</table>',
                                        '</div>',
                                    '</td>',
                                    '<td>',
                                        '&nbsp;',
                                    '</td>',
                                '</tr>',
                                '<tr>',
                                    '<td>',
                                        '<div style="margin-bottom:5px;">',
                                            '<table>',
                                                '<tr>',
                                                    '<td width="80px" style="align:left">Project #:</td>',
                                                    '<td><span>{ProjectNo}</span></td>',
                                                '</tr>',
                                            '</table>',
                                        '</div>',
                                    '</td>',
                                    '<td>',
                                        '&nbsp;',
                                    '</td>',
                                '</tr>',
                                '<tr>',
                                    '<td colspan="2">',
                                        '<div>',
                                            '<table>',
                                                '<tr>',
                                                    '<td width="80px" style="align:left">',
                                                        'Install:',
                                                    '</td>',
                                                    '<td>', 
                                                        '{InstallDate}',
                                                    '</td>',
                                                '</tr>',
                                            '</table>',
                                        '</div>',
                                    '</td>',
                                '</tr>',
                            '</table>',
                        '</div>',
                    '</td>',
                    '<td>',
                        '<div style="margin-left:40px">',
                            '<table>',
                                '<tr>',
                                    '<td width="80px" style="align:left;vertical-align:top">Technicians:</td>',
                                    '<td><div style="border: solid #cccccc 1px;width:350px;height:180px;overflow:auto;padding:2px">{Technician}</div></td>',
                                '</tr>',
                                '<tr>',
                                    '<td width="80px" style="align:left;vertical-align:top"><div style="margin-top:10px">Notes:</div></td>',
                                    '<td><div style="border: solid #cccccc 1px;width:350px;height:180px;overflow:auto;margin-top:10px;padding:2px">{Notes}</div></td>',
                                '</tr>',
                            '</table>',
                        '</div>',
                    '</td>',
                '</tr>',
            '</table>',
        '</div>',
        '<div style="height:15px;clear:left;float:left"></div>',
        '<div style="clear:left;float:left">',
            '<p style="font-size:14px;margin-left:25px"><b>Invoices</b></p>',
            '<div style="height:2px"></div>',
            '<tpl for="invoices">',
                '<div style="margin-bottom:35px;margin-top:10px">',
                    '<div style="margin-left:25px"><b>Invoice #: <span style="color:#2e408c">{InvoiceNo}</span></b></div>',
                    '<div style="margin-left:25px">Status: {PaymentStatusName}</div>',
                    '<div style="margin-left:25px">Type: {PaymentTypeName}',
                    '</div>',
                    '<tpl for="items">',
                        '<div style="margin-left:25px">',
                            '<div style="height:5px"></div>',
                            '<div><b>Item #: <span style="color:#000000">{ItemNo}</b></span>',
                            '</div>',
                            '<div>SKU: {SKU}</div>',
                            '<div>',
                                '<table>',
                                    '<tr>',
                                        '<td>',
                                            '<div style="margin-top:4px">Description</div>',
                                            '<div style="border: solid #cccccc 1px;width:350px;height:130px;overflow:auto;padding:2px">{Description}</div>',
                                        '</td>',
                                        '<td style="vertical-align:top">',
                                            '<div style="margin-left:15px;margin-top:15px;">Qty: {Quantity}</div>',
                                        '</td>',
                                        '<td style="vertical-align:top">',
                                            '<div style="margin-left:15px;margin-top:15px">Amount: ${Amount}</div>',
                                        '</td>',
                                    '</tr>',
                                '</table>',
                            '</div>',
                        '</div>',
                    '</tpl>',
                '</div>',
            '</tpl>',
        '</div>',
    '</div>',
'</tpl>',
{
    formatDate: function (value) {
        return Ext.Date.format(value, 'M j, Y');
    }
});


Ext.define('jobtracker.view.printjob', {
    extend: 'Ext.container.Container',
    itemId: 'printJob',
    layout: { type: 'hbox' },
    width: 700,

    initComponent: function () {
        this.items = this.buildItems();
        this.callParent();
    },


    buildItems: function () {
        return [{
                    xtype: 'container',
                    items: [{
                        autoScroll: true,
                        xtype: 'dataview',
                        emptyText: 'There are no jobs to display.',
                        itemId: 'printJobDataView',
                        width: 700,
                        tpl: defaultPrintJobTpl,
                        itemSelector: 'div.printJobSelectBox',
                        singleSelect: true
                    }]
                }]
        }
});
